import { useState } from 'react'

const DOCS = [
  {
    name: 'Course Registration Form',
    filename: 'course_registration_500L_2024.pdf',
    meta: 'PDF · 500 Level · 1st Semester 2024/2025',
    content: buildCourseFormPDF(),
  },
  {
    name: 'Examination Docket',
    filename: 'exam_docket_500L_2024.pdf',
    meta: 'PDF · Examination schedule · 2024/2025',
    content: buildDocketPDF(),
  },
]

function buildCourseFormPDF() {
  return `UNIVERSITY OF LAGOS
COURSE REGISTRATION FORM
Session: 2024/2025  |  Semester: 1st
Faculty: Engineering  |  Department: Computer Science
Level: 500  |  Student: Abigail

REGISTERED COURSES:
-------------------------------------------------
Code       Course Name                     Units
-------------------------------------------------
COS 501    Software Engineering              3
COS 503    Computer Networks                 3
COS 505    Artificial Intelligence           3
COS 507    Database Systems II               3
GST 501    Entrepreneurship                  3
ENG 301    Technical Writing                 3
COS 509    Machine Learning                  3
-------------------------------------------------
Total Credit Units: 21
-------------------------------------------------

Student Signature: _____________  Date: ___________
Adviser Signature: _____________  Date: ___________

This form was generated by CampusPal Portal Navigator.
`
}

function buildDocketPDF() {
  return `UNIVERSITY OF LAGOS
EXAMINATION DOCKET
Session: 2024/2025  |  Semester: 1st
Student: Abigail  |  Level: 500L  |  Dept: Computer Science

EXAMINATION SCHEDULE:
-------------------------------------------------------------
Course     Title                    Date         Time  Venue
-------------------------------------------------------------
COS 501    Software Engineering     Nov 18 2024  9am   ELT 1
COS 503    Computer Networks        Nov 20 2024  9am   ELT 2
COS 505    Artificial Intelligence  Nov 22 2024  1pm   LT 3
COS 507    Database Systems II      Nov 25 2024  9am   ELT 1
GST 501    Entrepreneurship         Nov 27 2024  1pm   LT 1
ENG 301    Technical Writing        Nov 29 2024  9am   A Block
COS 509    Machine Learning         Dec  2 2024  1pm   ELT 3
-------------------------------------------------------------

Bring this docket and a valid ID to every examination.
Generated by CampusPal Portal Navigator.
`
}

export default function DocCard({ visible }) {
  const [states, setStates] = useState(['idle', 'idle'])

  function handleDownload(idx) {
    setStates(prev => prev.map((s, i) => i === idx ? 'downloading' : s))
    setTimeout(() => {
      const doc = DOCS[idx]
      const blob = new Blob([doc.content], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = doc.filename
      a.click()
      URL.revokeObjectURL(url)
      setStates(prev => prev.map((s, i) => i === idx ? 'done' : s))
    }, 1200)
  }

  if (!visible) return null

  return (
    <div className="docs-container">
      {DOCS.map((doc, idx) => (
        <div className="doc-card" key={idx}>
          <div className="doc-icon">📄</div>
          <div className="doc-info">
            <div className="doc-name">{doc.name}</div>
            <div className="doc-meta">{doc.meta}</div>
          </div>
          <button
            className={`doc-download-btn${states[idx] === 'downloading' ? ' downloading' : ''}`}
            onClick={() => handleDownload(idx)}
            disabled={states[idx] === 'downloading'}
          >
            {states[idx] === 'idle' && '↓ Download'}
            {states[idx] === 'downloading' && 'Downloading…'}
            {states[idx] === 'done' && '✓ Saved'}
          </button>
        </div>
      ))}
    </div>
  )
}
